#!/bin/bash

TC_DIR=../share/ezvm
EZAS=../src/ezas/ezas

for f in `ls $TC_DIR`
do
	echo $f...
	$EZAS $TC_DIR/$f > /tmp/$f.out
	if [ -z `diff $f.outref /tmp/$f.out` ]
	then
		echo pass
		rm /tmp/$f.out
	else
		echo fail
		diff $f.outref /tmp/$f.out
	fi
done
